[workspace]
members = [
    "guaradict_core",
    "guaradict_server",
    "guaradict_client",
    "guaradict_nodejs"
]
resolver = "2"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
lto = true
